const formdate = {


  tec_email: [
    {
      label: "Alexsandro",
      value: "Alexsandro",
    },
    {
      label: "Gustavo",
      value: "Gustavo"
    },
    {
      label: "Allan",
      value: "Allan",
    },
    {
      label: "Fabio",
      value: "Fabio",
    },
    {
      label: "Thiago",
      value: "Thiago",
    },
  ] as const,

  cliente: [
    { label: '3 A CONSTRUTORA', value: '3 A CONSTRUTORA' },
    { label: 'AMBILIXO', value: 'AMBILIXO COLETA E TRANSPORTE DE RESIDUOS INDUSTRIAIS LTDA' },
    { label: 'ADEL', value: 'ADEL ADMINISTRACAO DE BENS LTDA' },
    { label: 'CARAVIERI', value: 'CARAVIERI ADMINISTRADORA PREDIAL LTDA' },
    { label: 'AGÊNCIA DE SITES', value: 'AGÊNCIA DE SITES' },
    { label: 'ALEXANDRE PODGAETI', value: 'ALEXANDRE PODGAETI' },
    { label: 'ALLIANCE', value: 'ALLIANCE DO BRASIL MAQUINAS DE LAVANDERIA LTDA' },
    { label: 'ALPHA GARDEN', value: 'ALPHA GARDEN - ASSESSORIA E NEGOCIOS IMOBILIARIOS LTDA' },
    { label: 'AR IMOBILIARIA', value: 'AR IMOBILIARIA LTDA' },
    { label: 'ARALPLAS', value: 'ARALPLAS LTDA' },
    { label: 'ATLANTICA', value: 'ATLANTICA IMOBILIARIA E ADMINISTRADORA SS LTDA' },
    { label: 'AXIS', value: 'AXIS SERVICOS FINANCEIROS LTDA' },
    { label: 'B3F CONTABILIDADE', value: 'B3F CONTABILIDADE' },
    { label: 'BIRK', value: 'BIRK INDUSTRIA E COMERCIO LTDA' },
    { label: 'BRADISFER', value: 'BRADISFER ATACADISTA DE FERRAGENS E FERRAMENTAS LTDA' },
    { label: 'BRAZ PAULO', value: 'BRAZ PAULO NICODEMO BUZATTO SERVICOS MEDICOS LTDA' },
    {
      label: 'CANDIDO EMPREENDIMENTOS',
      value: 'CANDIDO EMPREENDIMENTOS E PRESTAÇÃO DE SERVIÇOS LTDA'
    },
    { label: 'CAJE', value: 'CAJE MAQ E PRODUTOS PARA IND DE PANIF, CONF, E FOOD' },
    {
      label: 'CARVALHO & SICA',
      value: 'CARVALHO, SICA, MUSZKAT, VIDIGAL E CARNEIRO SOCIEDADE DE ADV'
    },
    { label: 'CBVE', value: 'CBVE TURISMO LTDA' },
    { label: 'CMED', value: 'CMED COMERCIO DE PRODUTOS HOSPITALARES LTDA' },
    { label: 'CONTABIL TRES S/S', value: 'CONTABIL TRES S/S' },
    { label: 'CRISTINA TAVARES', value: 'CRISTINA TAVARES DE SOUZA SILVA' },
    { label: 'DIOGO ADRIANO MARQUES', value: 'DIOGO ADRIANO MARQUES' },
    { label: 'DR1', value: 'DR1 EMPREENDIMENTOS IMOBILIARIOS LTDA' },
    { label: 'DRAKKAR', value: 'DRAKKAR INDUSTRIA DE DESCARTAVEIS E EPI LTDA' },
    { label: 'EQUACAO CONTABIL S/S', value: 'EQUACAO CONTABIL S/S' },
    { label: 'FLANOX', value: 'FLANOX COMERCIAL LTDA ME' },
    { label: 'FOCO EMPREENDIMENTOS', value: 'FOCO EMPREENDIMENTOS IMOBILIARIOS LTDA' },
    { label: 'FUNDIÇÃO SALTINHO', value: 'FUNDIÇÃO SALTINHO' },
    { label: 'GAMP', value: 'GAMP GRUPO DE ASSISTENCIA MEDICA PREVENTIVA LTDA' },
    { label: "GANT'S", value: "GANT'S INDUSTRIA E COMERCIOS DE ROUPAS" },
    { label: 'GIROSS', value: 'GIROSS PECAS E ACESSORIOS AUTOMOTIVOS LTDA' },
    { label: 'GSS', value: 'GSS SEGURANCA LTDA' },
    { label: 'IDEAL FEIRAS E EVENTOS', value: 'IDEAL FEIRAS E EVENTOS LTDA' },
    { label: 'INDUMAX', value: 'INDUMAX COMERCIO DE ACESSORIOS INDUSTRIAIS LTDA' },
    { label: 'INFORMBANK', value: 'INFORMBANK - BANCO DE INFORMACOES CADASTRAIS LTDA' },
    {
      label: 'INOVA GLASS',
      value: 'INOVA GLASS 1 INDUSTRIA DE VIDROS E PARTES OPACAS BLINDADOS LTDA'
    },
    { label: 'IIA BRASIL', value: 'IIA BRASIL' },
    { label: 'JUST TUR', value: 'JUST TUR OPERADORA DE TURISMO EIRELI' },
    { label: 'LICO IMOVEIS', value: 'LICO IMOVEIS LTDA' },
    { label: 'LIGHTING SERVIÇOS', value: 'LIGHTING SERVIÇOS LTDA (ANTIGA ZAC)' },
    { label: 'LIRAMAX ETIQUETAS', value: 'LIRAMAX ETIQUETAS LTDA' },
    {
      label: 'LIVANOVA BRASIL',
      value: 'LIVANOVA BRASIL COMERCIO E DISTRIBUICAO DE EQUIPAMENTOS MEDICOS LTDA'
    },
    { label: 'LUCIANO WERTHEIM', value: ' LUCIANO WERTHEIM EMPREENDIMENTOS IMOBILIARIOS LTDA' },
    { label: 'MAQUILINEA', value: 'MAQUILINEA-MAQUINAS E EQUIPAMENTOS RODOVIARIOS LTDA' },
    { label: 'MARIA ISABEL', value: 'MARIA ISABEL ARAUJO DE CASTRO' },
    { label: 'MHT', value: 'MHT INDUSTRIA E COMERCIO DE COMPONENTES AUTOMOTIVOS LTDA' },
    { label: 'MODESTO & ALMEIDA ADVOGADOS', value: 'MODESTO & ALMEIDA ADVOGADOS' },
    { label: 'ON MOB', value: 'ON MOB INTELIGÊNCIA IMOBILIÁRIA LTDA' },
    { label: 'PAULO AFONSO', value: 'PAULO AFONSO MARTINS DA SILVA' },
    { label: 'CROCCO', value: 'PAULO MONTEIRO & CROCCO MONTEIRO SOCIEDADE DE ADVOGADOS' },
    { label: 'PISSK', value: 'PISSK AGENCIA DE COMUNICACAO - EIRELI' },
    { label: 'POLEFLEX', value: 'POLEFLEX COMPONENTES INDUSTRIAIS LTDA' },
    { label: 'PUNTO E FILO', value: 'PUNTO E FILO INDUSTRIA E COMERCIO DE TAPETES' },
    { label: 'RANDON', value: 'RANDON INDUSTRIA E COMERCIO LTDA' },
    { label: 'RENOVA', value: 'RENOVA INDUSTRIA E COMERCIO DE CONDUTORES ELETRICOS' },
    { label: 'RECICLE', value: 'RECICLE SERVICOS DE LIMPEZA LTDA' },
    { label: 'RODMATEC', value: 'RODMATEC INDUSTRIA E COMERCIO LTDA' },
    { label: 'SAFETECH', value: 'SAFETECH ORGANIZACAO DOCUMENTAL LTDA' },
    { label: 'SCHMITZ E BARRETO LTDA', value: 'SCHMITZ E BARRETO LTDA' },
    { label: 'SCOLARI NETO & OLIVEIRA', value: 'SCOLARI NETO & OLIVEIRA' },
    { label: 'SERPAC', value: 'SERPAC COMERCIO E INDUSTRIA LTDA' },
    { label: 'SETEC', value: 'SETEC SERVIÇO TECNICO CONTABIL LTDA' },
    { label: 'SITE AGENCIA DIGITAL', value: 'SITE AGENCIA DIGITAL' },
    { label: 'SNV ASSESSORIA', value: 'SNV ASSESSORIA TRIBUTARIA LTDA' },
    { label: 'SOCIEDADE 21 DE ABRIL', value: 'SOCIEDADE BENEFICIENTE MIXTA MORTUARIA 21 DE  ABRIL' },
    { label: 'SORRIA VITTA', value: 'SORRIA VITTA ODONTOLOGIA INTEGRADA LTDA' },
    { label: 'T&A', value: 'T&A CONSTRUÇÃO PRÉ FABRICADA S/A' },
    { label: 'TECNEW', value: 'TECNEW ELEVADORES, COMERCIO E ASSISTENCIA TÉCNICA LTDA' },
    { label: 'TECNOPONTA', value: 'TECNOPONTA CINE VIDEO LTDA' },
    { label: 'TIME E LIFE', value: 'TIME E LIFE INVESTIMENTOS IMOBILIARIOS LTDA' },
    { label: 'TOP DOWN', value: 'TOP DOWN CONSULTORIA & PROJETOS S.A' },
    { label: 'TRANSMAREAR', value: 'TRANSMAREAR CARGO LOGISTICA INTERNACIONAL LTDA' },
    {
      label: 'TROUW',
      value: 'TROUW TECNOLOGIA PARA MOBILIDADE, VISIBILIDADE E GESTAO DE REDES LTDA'
    },
    { label: 'UNICLIN', value: 'UNICLIN CENTRO MEDICO INTEGRADO A SAUDE' },
    { label: 'UNIVERSAL AUTO IMPORTS EIRELI', value: 'UNIVERSAL AUTO IMPORTS EIRELI' },
    { label: 'VACHILESKI', value: 'VACHILESKI RECAUCHUTADORA DE PNEUS MT LTDA' },
    { label: 'YUPPIE', value: 'YUPPIE AUDITORIA CONSULTORIA E PERICIAS LTDA' }
  ] as const,

  def: [
    { label: "NÃO REALIZA CHAMADAS INTERNAS", value: "NÃO REALIZA CHAMADAS INTERNAS" },
    { label: "NÃO REALIZA CHAMADAS EXTERNAS", value: "NÃO REALIZA CHAMADAS EXTERNAS" },
    { label: "RAMAL SEM REGISTRO", value: "RAMAL SEM REGISTRO" },
    { label: "CADASTRO DE NOVO RAMAL", value: "CADASTRO DE NOVO RAMAL" },
    { label: "ALTERAÇÕES GERAIS NO SISTEMA", value: "ALTERAÇÕES GERAIS NO SISTEMA" },
    { label: "AJUSTE OU CONFIGURAÇÃO NO DISPOSITIVO FINAL", value: "AJUSTE OU CONFIGURAÇÃO NO DISPOSITIVO FINAL" },
    { label: "TREINAMENTO", value: "TREINAMENTO" },
    { label: "DÚVIDAS EM GERAL", value: "DÚVIDAS EM GERAL" },
    { label: "SOLICITAÇÃO DE GRAVAÇÕES", value: "SOLICITAÇÃO DE GRAVAÇÕES" },
    { label: "CONTRATAÇÃO DE SERVIÇO E/OU EQUIPAMENTOS", value: "CONTRATAÇÃO DE SERVIÇO E/OU EQUIPAMENTOS" },
    { label: "NÃO RECEBE LIGAÇÕES (CELULAR)", value: "NÃO RECEBE LIGAÇÕES (CELULAR)" },
    { label: "NÃO RECEBE LIGAÇÕES (TELEFONE)", value: "NÃO RECEBE LIGAÇÕES (TELEFONE)" },
    { label: "NÃO RECEBE LIGAÇÕES (COMPUTADOR)", value: "NÃO RECEBE LIGAÇÕES (COMPUTADOR)" },
    { label: "REATIVAÇÃO DE RAMAL NO DISPOSITIVO FINAL", value: "REATIVAÇÃO DE RAMAL NO DISPOSITIVO FINAL" },
    { label: "RAMAL OU RAMAIS NÃO TRANSFEREM CHAMADAS", value: "RAMAL OU RAMAIS NÃO TRANSFEREM CHAMADAS" },
    { label: "FALHA DE LIGAÇÕES (EXTERNAS/INTERNAS)", value: "FALHA DE LIGAÇÕES (EXTERNAS/INTERNAS)" },
    { label: "ALTERAÇÃO NA ORDEM DE TOQUE", value: "ALTERAÇÃO NA ORDEM DE TOQUE" },
    { label: "TROCA DE TELEFONE/HEADSET/CABOS/FONTES", value: "TROCA DE TELEFONE/HEADSET/CABOS/FONTES" },
    { label: "SOLICITAÇÃO DE RELATÓRIO", value: "SOLICITAÇÃO DE RELATÓRIO" },
    { label: "ALTERAÇÃO DE DADOS DE RAMAL/COLABORADOR", value: "ALTERAÇÃO DE DADOS DE RAMAL/COLABORADOR" },
    { label: "OPÇÃO DA URA NÃO FUNCIONA", value: "OPÇÃO DA URA NÃO FUNCIONA" },
    { label: "RAMAL COM CHIADO / RUIDO", value: "RAMAL COM CHIADO / RUIDO" },
    { label: "RAMAL SEM ÁUDIO", value: "RAMAL SEM ÁUDIO" },
    { label: "RAMAL SEM TOQUE", value: "RAMAL SEM TOQUE" },
    { label: "SOLICITAÇÃO DE ATIVAÇÃO DO WHATSAPP", value: "SOLICITAÇÃO DE ATIVAÇÃO DO WHATSAPP" }
  ] as const,

  diags: [
    { label: 'SERVIDOR DE HOSPEDAGEM INOPERANTE', value: 'SERVIDOR DE HOSPEDAGEM INOPERANTE' },
    { label: 'TRONCO INOPERANTE', value: 'TRONCO INOPERANTE' },
    { label: 'DISPOSITIVO FINAL SEM REDE', value: 'DISPOSITIVO FINAL SEM REDE' },
    { label: 'DISPOSITIVO FINAL INOPERANTE', value: 'DISPOSITIVO FINAL INOPERANTE' },
    { label: 'ERRO DE CONFIGURAÇÃO (SISTEMA OU DISPOSITIVO)', value: 'ERRO DE CONFIGURAÇÃO (SISTEMA OU DISPOSITIVO)' },
    { label: 'DEFEITO EXTERNO (PROVEDOR INTERNET, LINHA OU INFRA DO CLIENTE)', value: 'DEFEITO EXTERNO (PROVEDOR INTERNET, LINHA OU INFRA DO CLIENTE)' },
    { label: 'SERVIDOR SBC INOPERANTE', value: 'SERVIDOR SBC INOPERANTE' },
    { label: 'SERVIÇOS DO SERVIDOR "PARADOS"', value: 'SERVIÇOS DO SERVIDOR "PARADOS"' },
    { label: 'APP OU PROGRAMA DO 3CX NÃO REGISTRA (COMPUTADOR/CELULAR)', value: 'APP OU PROGRAMA DO 3CX NÃO REGISTRA (COMPUTADOR/CELULAR)' },
    { label: 'TROCA DE PROTOCOLO (UDP OU TCP)', value: 'TROCA DE PROTOCOLO (UDP OU TCP)' },
    { label: 'TROCA DE FAIXA IP LOCAL (CLIENTE)', value: 'TROCA DE FAIXA IP LOCAL (CLIENTE)' },
    { label: 'ALTERAÇÃO DE PARÂMETRO NO 3CX', value: 'ALTERAÇÃO DE PARÂMETRO NO 3CX' },
    { label: 'ERRO NA OPERAÇÃO COM A PLATAFORMA', value: 'ERRO NA OPERAÇÃO COM A PLATAFORMA' },
    { label: 'PROVISIONAMENTO EM DISPOSITIVO FINAL', value: 'PROVISIONAMENTO EM DISPOSITIVO FINAL' },
    { label: 'INSTABILIDADE DE CONEXÃO COM SERVIDOR (PABX/OPERADORA)', value: 'INSTABILIDADE DE CONEXÃO COM SERVIDOR (PABX/OPERADORA)' },
    { label: 'ORIENTAÇÃO TÉCNICA', value: 'ORIENTAÇÃO TÉCNICA' },
    { label: 'EFETUADO TROCA DE TELEFONE/HEADSET/FONTE/CABO', value: 'EFETUADO TROCA DE TELEFONE/HEADSET/FONTE/CABO' },
    { label: 'TROCA DE CABOS (REDE/LISO/ESPIRAL)', value: 'TROCA DE CABOS (REDE/LISO/ESPIRAL)' },
    { label: 'CONFIGURAÇÕES INCORRETAS NA NVOIP', value: 'CONFIGURAÇÕES INCORRETAS NA NVOIP' },
    { label: 'ENVIO DE ARQUIVOS', value: 'ENVIO DE ARQUIVOS' },
    { label: 'PROVISIONAMENTO DO APLICATIVO MOVEL OU DESKTOP', value: 'PROVISIONAMENTO DO APLICATIVO MOVEL OU DESKTOP' },
  ] as const,

  role : [
    {label: "Administrador", value: "Administrador"},
    {label: "Tecnico Interno", value: "Tecnico Interno"},
    {label: "Tecnico Externo", value: "Tecnico Externo"}
  ] as const
}




export default formdate;   